---
# Работать в кластере нужно не от root, поэтому создаём пользователя
- name: Create user '{{ user_name }}'
  user:
    name: "{{ user_name }}"
    shell: /bin/bash
    groups: wheel
    append: yes
    generate_ssh_key: yes

# и копируем ему нужные ssh-ключи
- name: Copy authorized keys for user '{{ user_name }}'
  copy:
    src: roles/kuber/files/authorized_keys
    dest: /home/{{ user_name }}/.ssh/authorized_keys

# Инициализируем кластер
- name: Initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

# Получаем команду, для подключения рабочих нод
- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

# и сохраняем её в факты ansible
- name: Set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

# Создаём папку, где будет храниться конфиг кубера
- name: Create .kube directory
  become: yes
  become_user: "{{ user_name }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

# и копируем его туда
- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ user_name }}/.kube/config
    remote_src: yes
    owner: "{{ user_name }}"

# Копируем на master-ноду плейбуки за запуска внутренней сети и WebUI
- name: Copy kube-flannel.yml, dashboard.yml and dashboard-admin.yml
  become: yes
  become_user: "{{ user_name }}"
  copy:
    src: roles/kuber/files/{{ item }}
    dest: $HOME/{{ item }}
  with_items:
    - kube-flannel.yml
    - dashboard.yml
    - dashboard-admin.yml

# Запускаем внутреннюю сеть кубера на базе flannel
- name: Install Pod network
  become: yes
  become_user: "{{ user_name }}"
  shell: kubectl apply -f kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

# Ставим Dashboard для управления кластером через web
- name: Install Dashboard
  become: yes
  become_user: "{{ user_name }}"
  shell: kubectl apply -f dashboard.yml > dashboard.txt
  args:
    chdir: $HOME

# Создаём админский аккаунт для доступа в Dashboard
- name: Create Dashboard admin account
  become: yes
  become_user: "{{ user_name }}"
  shell: kubectl apply -f dashboard-admin.yml > dashboard-admin.txt
  args:
    chdir: $HOME

# Получаем админский токен и сохраняем его в файл.
# Потом его нужно будет оттуда скопипастить в WebUI при авторизации
- name: Get Dashboard admin account token
  become: yes
  become_user: "{{ user_name }}"
  shell: >
    kubectl -n kube-system describe secret $(kubectl -n kube-system get secret |
    grep admin-user | awk '{print $1}') > admin-token.txt
  args:
    chdir: $HOME

# Создаём crontab для запуска Dashboard при каждой перезагрузке сервера
- name: Create crontab for start Dashboard after reboot server
  become: yes
  become_user: "{{ user_name }}"
  cron:
    name: "a job for reboot"
    special_time: reboot
    job: screen -d -m kubectl proxy

# и запускаем Dashboard
- name: Start Dashboard
  become: yes
  become_user: "{{ user_name }}"
  shell: screen -d -m kubectl proxy
